name: Compress Images on Push to Master with Commit
on:
  push:
    branches:
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.TOKEN }}
          compressOnly: true
      - name: Commit changes direct to master
        run: |
          echo "Committing compressed images"
          git config --global user.email "875499765@qq.com"
          git config --global user.name "guanpengchn"
          git diff-index --quiet HEAD || git commit -am "Compressing images"
          git push